# Generated by Django 6.0.2 on 2026-03-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='tipo_consulta',
            field=models.CharField(default='Fisioterapia', max_length=100),
        ),
        migrations.AddField(
            model_name='sessao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
